### ISSUE TITLE
Do I need to install Monokai

### ISSUE THREAD

**Issue by stephdl** [grigio/vim-sublime#5]
You say 'Don't worry about the 'Monokai' error' but after the tutorial you gave, each time I used vim I have had this error at the beginning until I installed  https://github.com/lsdr/monokai.

Is it a lack in your tutorial or I have misunderstood it or misconfigured vim

**Comment by curtisullerich** [comment]
Since this error is still present on new installs, I'll share my workaround. It seems to be a case sensitivity issue. After installing, the color file for Monokai is ~/.vim/bundle/vim-colorschemes/colors/Monokai.vim. At some point "monokai.vim" is expected. Rename Monokai.vim to monokai.vim and see if that helps.

**Comment by grigio** [comment]
If you want submit a PR
